### ISSUE TITLE
Minor issue with Wiki

### ISSUE THREAD

**Issue by alekmark** [gunjandatta/gd-sprest-bs-starter#1]
Hi @gunjandatta ,

Wiki page under [Demo step 5 ](https://github.com/gunjandatta/sprest-bs-starter/wiki/Step-5),  the code block under JavaScript [step 2](https://github.com/gunjandatta/sprest-bs-starter/wiki/Step-5#2-reference-the-solution) and 3 doesn't match the screenshots of how to deploy. I believe the path to project.js file is local VS the one you upload to your SharePoint site assets folder.

**Comment by gunjandatta** [comment]
Thanks for reporting this, I updated the last page. Let me know if anything else is incorrect or unclear.
